[package]
name = "generation"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
noise = { version = "0.9.0", features = ["images"] }
pollster = "0.4.0"
wgpu = "23.0.1"
winit = "0.29"
